### ISSUE TITLE
Incorrect git clone command in tutorial

### ISSUE THREAD

**Issue by smoes-prime** [TuomoKalliokoski/HASTEN#3]
The tutorial includes a command:
git clone https://github.com/TuomoKalliokoski/HASTEN -b v1.1

which produces a fatal error, it should be:
git clone -b version1.1 https://github.com/TuomoKalliokoski/HASTEN

Best Regards,
Sebastian

**Comment by TuomoKalliokoski** [comment]
Hello Sebastian,

thanks for reporting this, fixed!

Bes regards,
Tuomo
